### ISSUE TITLE
Does not correctly join paths on Windows

### ISSUE THREAD

**Issue by bricketts-authentify** [cheton/browserify-css#27]
When running Node/Browserify on Windows, CSS paths (such as in ```url()``` values) do not get formatted correctly. ```path.join``` formats paths with a backslash (```\```) on Windows, which does not get escaped when written to the CSS, causing the browser to request an invalid path.

Example:
```css
@font-face {
    ...
    src: url("../fonts/material-icons.ttf");
    ...
}
```
in the source CSS file gets turned into
```css
@font-face {
    ...
    src: url(fonts\material-icons.ttf);
    ...
}
```
in the transformed CSS file, which Firefox requests as
```
~/fontsmaterial-icons.ttf
```
which obviously is not correct.

One solution would be to use the path-posix module to always use forward slashes (```/```) even when on Windows.
